@startumltitle Empty Diagram - LMS_Flujostart:Inicio de Sesión;if (¿Es Administrador?) then (yes)    :Redirigir a loginAdmin.php;    :Validar Credenciales;    if (¿Credenciales Válidas?) then (yes)        :Redirigir a Admin Dashboard;        :Mostrar Panel de Administración;        :Gestionar Libros, Autores y Categorías;        :Ver Préstamos;    else (no)        :Mostrar Error de Inicio de Sesión;    endifelse (no)    :Redirigir a loginStudent.php;    :Validar Credenciales;    if (¿Credenciales Válidas?) then (yes)        :Redirigir a Student Dashboard;        :Mostrar Panel de Estudiante;        :Buscar y Prestar Libros;        :Ver Libros Prestados;        :Devolver Libros;    else (no)        :Mostrar Error de Inicio de Sesión;    endifendifstop@enduml